# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_management.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user_management.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15user_management.proto\x12\x0eusermanagement\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"8\n\x12\x43reateUserResponse\x12\"\n\x04user\x18\x01 \x01(\x0b\x32\x14.usermanagement.User\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"5\n\x0fGetUserResponse\x12\"\n\x04user\x18\x01 \x01(\x0b\x32\x14.usermanagement.User\"<\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"8\n\x12UpdateUserResponse\x12\"\n\x04user\x18\x01 \x01(\x0b\x32\x14.usermanagement.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe2\x02\n\x15UserManagementService\x12S\n\nCreateUser\x12!.usermanagement.CreateUserRequest\x1a\".usermanagement.CreateUserResponse\x12J\n\x07GetUser\x12\x1e.usermanagement.GetUserRequest\x1a\x1f.usermanagement.GetUserResponse\x12S\n\nUpdateUser\x12!.usermanagement.UpdateUserRequest\x1a\".usermanagement.UpdateUserResponse\x12S\n\nDeleteUser\x12!.usermanagement.DeleteUserRequest\x1a\".usermanagement.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=41
  _globals['_USER']._serialized_end=88
  _globals['_CREATEUSERREQUEST']._serialized_start=90
  _globals['_CREATEUSERREQUEST']._serialized_end=138
  _globals['_CREATEUSERRESPONSE']._serialized_start=140
  _globals['_CREATEUSERRESPONSE']._serialized_end=196
  _globals['_GETUSERREQUEST']._serialized_start=198
  _globals['_GETUSERREQUEST']._serialized_end=226
  _globals['_GETUSERRESPONSE']._serialized_start=228
  _globals['_GETUSERRESPONSE']._serialized_end=281
  _globals['_UPDATEUSERREQUEST']._serialized_start=283
  _globals['_UPDATEUSERREQUEST']._serialized_end=343
  _globals['_UPDATEUSERRESPONSE']._serialized_start=345
  _globals['_UPDATEUSERRESPONSE']._serialized_end=401
  _globals['_DELETEUSERREQUEST']._serialized_start=403
  _globals['_DELETEUSERREQUEST']._serialized_end=434
  _globals['_DELETEUSERRESPONSE']._serialized_start=436
  _globals['_DELETEUSERRESPONSE']._serialized_end=473
  _globals['_USERMANAGEMENTSERVICE']._serialized_start=476
  _globals['_USERMANAGEMENTSERVICE']._serialized_end=830
# @@protoc_insertion_point(module_scope)
